---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: 
         - apache2
         - libapache2-mod-php
         - htop
         - cmatrix
      state: latest
    when: ansible_distribution == "Ubuntu"
