---
- name: Setup Apache on RedHat
  hosts: redhat
  become: yes
  tasks:
    - name: Install Apache (httpd)
      dnf:
        name: httpd
        state: present

    - name: Enable and Start Apache Service
      systemd:
        name: httpd
        enabled: yes
        state: started

    - name: Allow HTTP Traffic in Firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Reload Firewall to Apply Changes
      command: firewall-cmd --reload
