---
- name: Install Apache (apache2)
  package:
    name: apache2
    state: present

- name: Start and enable Apache service
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true

- name: Set correct permissions for Debian
  ansible.builtin.file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes