---
- name: Install Apache (httpd)
  package:
    name: httpd
    state: present

- name: Start and enable Apache service
  ansible.builtin.systemd:
    name: httpd
    state: started
    enabled: true

- name: Set correct permissions for RedHat
  ansible.builtin.file:
    path: /var/www/html
    owner: apache
    group: apache
    recurse: yes