version: '3.9'
services:
  app1:
    build: .
    container_name: codeshare_app1
    ports:
      - "3001:3000"
    volumes:
      - ./rooms:/app/rooms

  app2:
    build: .
    container_name: codeshare_app2
    ports:
      - "3002:3000"
    volumes:
      - ./rooms:/app/rooms

  app3:
    build: .
    container_name: codeshare_app3
    ports:
      - "3003:3000"
    volumes:
      - ./rooms:/app/rooms

  nginx:
    image: nginx:latest
    container_name: codeshare_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-cert:/etc/nginx/ssl:ro
    ports:
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
